name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Print release version
        id: bump_version
        uses: gustavo1020/-release-version-@v1.0.0-stable
        with:
          list-version-fragment: ${{secret.LIST-VERSIONS-FRAGMENTS}}
          prefix: "v"

      - name: Print release version
        run: echo ${{ steps.bump_version.outputs.next-version }}
